### ISSUE TITLE
CloudPassage Halo Detected Issues on Build

### ISSUE THREAD

**Issue by ashmastaflash** [ashmastaflash/don-dash#1]
### Critical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| file_owner_uid | root | root | /etc/passwd |
| file_owner_gid | root | root | /etc/passwd |
| file_acl | 644 | 644 | /etc/passwd |
| file_owner_uid | root | root | /etc/shadow |
| file_owner_gid | root | shadow | /etc/shadow |
| file_acl | NOT: 1**,2**,3**,5**,6**,7**,*1*,*2*,*3*,*4*,*5*,*6*,*7*,**1,**2,**3,**4,**5,**6,**7 | 640 | /etc/shadow |

### Critical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| file_acl | 600 | 640 | /var/log/auth.log |
| file_acl | 600 | 640 | /var/log/syslog |
| file_owner_uid | root | root | /var/log/auth.log |
| file_owner_uid | root | root | /var/log/syslog |
| file_owner_gid | root | adm | /var/log/auth.log |
| file_owner_gid | root | adm | /var/log/syslog |

### Critical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| configuration | NOT: yes | yes | /etc/ssh/sshd_config |

### Critical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| dir_owner_uid | root | root | /etc/cron.daily |
| dir_owner_uid | root | root | /etc/cron.hourly |
| dir_owner_uid | root | root | /etc/cron.d |
| dir_owner_uid | root | root | /etc/cron.monthly |
| dir_owner_uid | root | root | /etc/cron.weekly |
| dir_owner_gid | root | root | /etc/cron.d |
| dir_owner_gid | root | root | /etc/cron.monthly |
| dir_owner_gid | root | root | /etc/cron.weekly |
| dir_owner_gid | root | root | /etc/cron.daily |
| dir_owner_gid | root | root | /etc/cron.hourly |
| dir_acl | NOT: **2,**3,**6,**7 | 755 | /etc/cron.hourly |
| dir_acl | NOT: **2,**3,**6,**7 | 755 | /etc/cron.daily |
| dir_acl | NOT: **2,**3,**6,**7 | 755 | /etc/cron.weekly |
| dir_acl | NOT: **2,**3,**6,**7 | 755 | /etc/cron.monthly |
| dir_acl | NOT: **2,**3,**6,**7 | 755 | /etc/cron.d |
| file_owner_uid | root | None | /etc/cron.hourly/* |
| file_owner_uid | root | root | /etc/cron.daily/apache2 |
| file_owner_uid | root | root | /etc/cron.daily/apt |
| file_owner_uid | root | root | /etc/cron.daily/aptitude |
| file_owner_uid | root | root | /etc/cron.daily/bsdmainutils |
| file_owner_uid | root | root | /etc/cron.daily/dpkg |
| file_owner_uid | root | root | /etc/cron.daily/logrotate |
| file_owner_uid | root | root | /etc/cron.daily/man-db |
| file_owner_uid | root | root | /etc/cron.daily/mlocate |
| file_owner_uid | root | root | /etc/cron.daily/passwd |
| file_owner_uid | root | root | /etc/cron.weekly/man-db |
| file_owner_uid | root | None | /etc/cron.monthly/* |
| file_owner_uid | root | None | /etc/cron.d/* |
| file_owner_gid | root | None | /etc/cron.hourly/* |
| file_owner_gid | root | root | /etc/cron.daily/apache2 |
| file_owner_gid | root | root | /etc/cron.daily/apt |
| file_owner_gid | root | root | /etc/cron.daily/aptitude |
| file_owner_gid | root | root | /etc/cron.daily/bsdmainutils |
| file_owner_gid | root | root | /etc/cron.daily/dpkg |
| file_owner_gid | root | root | /etc/cron.daily/logrotate |
| file_owner_gid | root | root | /etc/cron.daily/man-db |
| file_owner_gid | root | root | /etc/cron.daily/mlocate |
| file_owner_gid | root | root | /etc/cron.daily/passwd |
| file_owner_gid | root | root | /etc/cron.weekly/man-db |
| file_owner_gid | root | None | /etc/cron.monthly/* |
| file_owner_gid | root | None | /etc/cron.d/* |
| file_acl | NOT: **2,**3,**6,**7 | None | /etc/cron.hourly/* |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/cron.daily/apache2 |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/cron.daily/apt |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/cron.daily/aptitude |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/cron.daily/bsdmainutils |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/cron.daily/dpkg |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/cron.daily/logrotate |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/cron.daily/man-db |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/cron.daily/mlocate |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/cron.daily/passwd |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/cron.weekly/man-db |
| file_acl | NOT: **2,**3,**6,**7 | None | /etc/cron.monthly/* |
| file_acl | NOT: **2,**3,**6,**7 | None | /etc/cron.d/* |

### Noncritical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| file_regex | True | False | /etc/pam.d/common-password |
| file_regex | True | False | /etc/pam.d/common-password |
| file_regex | True | False | /etc/pam.d/common-password |
| file_regex | True | False | /etc/pam.d/sshd |

### Noncritical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| dir_sticky_bit | 0 | 6 | stickybit |

### Noncritical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| user_home_file_ownership | 0 | 0 | root |
| user_home_file_ownership | 0 | 0 | games |
| user_home_file_ownership | 0 | 0 | man |
| user_home_file_ownership | 0 | None | lp |
| user_home_file_ownership | 0 | 0 | mail |
| user_home_file_ownership | 0 | None | news |
| user_home_file_ownership | 0 | None | uucp |
| user_home_file_ownership | 0 | 105 | proxy |
| user_home_file_ownership | 0 | 1 | www-data |
| user_home_file_ownership | 0 | None | list |
| user_home_file_ownership | 0 | None | irc |
| user_home_file_ownership | 0 | None | gnats |
| user_home_file_ownership | 0 | 0 | libuuid |
| user_home_file_ownership | 0 | 0 | sshd |
| user_home_file_ownership | 0 | 0 | admin |

### Noncritical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| user_file_presence | False | False | root |
| user_file_presence | False | False | daemon |
| user_file_presence | False | False | bin |
| user_file_presence | False | False | sys |
| user_file_presence | False | False | sync |
| user_file_presence | False | False | games |
| user_file_presence | False | False | man |
| user_file_presence | False | None | lp |
| user_file_presence | False | False | mail |
| user_file_presence | False | None | news |
| user_file_presence | False | None | uucp |
| user_file_presence | False | False | proxy |
| user_file_presence | False | False | www-data |
| user_file_presence | False | False | backup |
| user_file_presence | False | None | list |
| user_file_presence | False | None | irc |
| user_file_presence | False | None | gnats |
| user_file_presence | False | False | libuuid |
| user_file_presence | False | False | sshd |
| user_file_presence | False | False | admin |

### Noncritical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| user_home_files_detect_path_statements | False | False | root |
| user_home_files_detect_path_statements | False | False | daemon |
| user_home_files_detect_path_statements | False | False | bin |
| user_home_files_detect_path_statements | False | False | sys |
| user_home_files_detect_path_statements | False | False | sync |
| user_home_files_detect_path_statements | False | False | games |
| user_home_files_detect_path_statements | False | False | man |
| user_home_files_detect_path_statements | False | None | lp |
| user_home_files_detect_path_statements | False | False | mail |
| user_home_files_detect_path_statements | False | None | news |
| user_home_files_detect_path_statements | False | None | uucp |
| user_home_files_detect_path_statements | False | False | proxy |
| user_home_files_detect_path_statements | False | False | www-data |
| user_home_files_detect_path_statements | False | False | backup |
| user_home_files_detect_path_statements | False | None | list |
| user_home_files_detect_path_statements | False | None | irc |
| user_home_files_detect_path_statements | False | None | gnats |
| user_home_files_detect_path_statements | False | False | libuuid |
| user_home_files_detect_path_statements | False | False | sshd |
| user_home_files_detect_path_statements | False | False | admin |

### Noncritical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| user_home_device_files | 0 | 0 | root |
| user_home_device_files | 0 | 0 | daemon |
| user_home_device_files | 0 | 0 | bin |
| user_home_device_files | 0 | 0 | sync |
| user_home_device_files | 0 | 0 | games |
| user_home_device_files | 0 | 0 | man |
| user_home_device_files | 0 | None | lp |
| user_home_device_files | 0 | 0 | mail |
| user_home_device_files | 0 | None | news |
| user_home_device_files | 0 | None | uucp |
| user_home_device_files | 0 | 0 | proxy |
| user_home_device_files | 0 | 0 | www-data |
| user_home_device_files | 0 | 0 | backup |
| user_home_device_files | 0 | None | list |
| user_home_device_files | 0 | None | irc |
| user_home_device_files | 0 | None | gnats |
| user_home_device_files | 0 | 0 | libuuid |
| user_home_device_files | 0 | 0 | sshd |
| user_home_device_files | 0 | 0 | admin |

### Noncritical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| user_file_presence | False | False | root |
| user_file_presence | False | False | daemon |
| user_file_presence | False | False | bin |
| user_file_presence | False | False | sys |
| user_file_presence | False | False | sync |
| user_file_presence | False | False | games |
| user_file_presence | False | False | man |
| user_file_presence | False | None | lp |
| user_file_presence | False | False | mail |
| user_file_presence | False | None | news |
| user_file_presence | False | None | uucp |
| user_file_presence | False | False | proxy |
| user_file_presence | False | False | www-data |
| user_file_presence | False | False | backup |
| user_file_presence | False | None | list |
| user_file_presence | False | None | irc |
| user_file_presence | False | None | gnats |
| user_file_presence | False | False | libuuid |
| user_file_presence | False | False | sshd |
| user_file_presence | False | False | admin |

### Critical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| dir_acl | NOT: **2,**3,**6,**7 | 755 | /var/spool/cron |
| dir_owner_uid | root | root | /var/spool/cron |
| dir_owner_gid | root | root | /var/spool/cron |

### Critical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| configuration | 2 | 2 | /etc/ssh/sshd_config |
| configuration | NOT: no | yes | /etc/ssh/sshd_config |
| configuration | NOT: yes | no | /etc/ssh/sshd_config |
| configuration | NOT: yes | no | /etc/ssh/sshd_config |

### Critical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| configuration | NOT: yes | no | /etc/ssh/sshd_config |

### Critical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| configuration | 0 | 0 | /proc/sys/net/ipv4/conf/all/accept_source_route |
| configuration | NOT: 1 | None | /etc/sysctl.conf |

### Critical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| process_presence | true | true | rsyslogd |

### Critical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| file_presence | False | False | /etc/hosts.equiv |

### Critical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| file_presence | False | False | /root/.rhosts |
| file_presence | False | False | /root/rhosts |

### Critical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| configuration | 0 | 0 | /proc/sys/net/ipv4/ip_forward |

### Critical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| dir_owner_uid | root | root | /etc/init.d |
| dir_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d |
| file_owner_uid | root | root | /etc/init.d/README |
| file_owner_uid | root | root | /etc/init.d/apache2 |
| file_owner_uid | root | root | /etc/init.d/bootlogs |
| file_owner_uid | root | root | /etc/init.d/bootmisc.sh |
| file_owner_uid | root | root | /etc/init.d/checkfs.sh |
| file_owner_uid | root | root | /etc/init.d/checkroot-bootclean.sh |
| file_owner_uid | root | root | /etc/init.d/checkroot.sh |
| file_owner_uid | root | root | /etc/init.d/cloud-config |
| file_owner_uid | root | root | /etc/init.d/cloud-final |
| file_owner_uid | root | root | /etc/init.d/cloud-init |
| file_owner_uid | root | root | /etc/init.d/cloud-init-local |
| file_owner_uid | root | root | /etc/init.d/cphalod |
| file_owner_uid | root | root | /etc/init.d/cron |
| file_owner_uid | root | root | /etc/init.d/halt |
| file_owner_uid | root | root | /etc/init.d/hostname.sh |
| file_owner_uid | root | root | /etc/init.d/hwclock.sh |
| file_owner_uid | root | root | /etc/init.d/killprocs |
| file_owner_uid | root | root | /etc/init.d/kmod |
| file_owner_uid | root | root | /etc/init.d/motd |
| file_owner_uid | root | root | /etc/init.d/mountall-bootclean.sh |
| file_owner_uid | root | root | /etc/init.d/mountall.sh |
| file_owner_uid | root | root | /etc/init.d/mountdevsubfs.sh |
| file_owner_uid | root | root | /etc/init.d/mountkernfs.sh |
| file_owner_uid | root | root | /etc/init.d/mountnfs-bootclean.sh |
| file_owner_uid | root | root | /etc/init.d/mountnfs.sh |
| file_owner_uid | root | root | /etc/init.d/mtab.sh |
| file_owner_uid | root | root | /etc/init.d/networking |
| file_owner_uid | root | root | /etc/init.d/procps |
| file_owner_uid | root | root | /etc/init.d/rc |
| file_owner_uid | root | root | /etc/init.d/rc.local |
| file_owner_uid | root | root | /etc/init.d/rcS |
| file_owner_uid | root | root | /etc/init.d/reboot |
| file_owner_uid | root | root | /etc/init.d/rmnologin |
| file_owner_uid | root | root | /etc/init.d/rsyslog |
| file_owner_uid | root | root | /etc/init.d/screen-cleanup |
| file_owner_uid | root | root | /etc/init.d/sendsigs |
| file_owner_uid | root | root | /etc/init.d/single |
| file_owner_uid | root | root | /etc/init.d/skeleton |
| file_owner_uid | root | root | /etc/init.d/ssh |
| file_owner_uid | root | root | /etc/init.d/sudo |
| file_owner_uid | root | root | /etc/init.d/udev |
| file_owner_uid | root | root | /etc/init.d/udev-mtab |
| file_owner_uid | root | root | /etc/init.d/umountfs |
| file_owner_uid | root | root | /etc/init.d/umountnfs.sh |
| file_owner_uid | root | root | /etc/init.d/umountroot |
| file_owner_uid | root | root | /etc/init.d/unattended-upgrades |
| file_owner_uid | root | root | /etc/init.d/urandom |
| file_acl | NOT: **2,**3,**6,**7 | 644 | /etc/init.d/README |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/apache2 |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/bootlogs |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/bootmisc.sh |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/checkfs.sh |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/checkroot-bootclean.sh |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/checkroot.sh |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/cloud-config |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/cloud-final |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/cloud-init |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/cloud-init-local |
| file_acl | NOT: **2,**3,**6,**7 | 750 | /etc/init.d/cphalod |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/cron |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/halt |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/hostname.sh |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/hwclock.sh |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/killprocs |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/kmod |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/motd |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/mountall-bootclean.sh |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/mountall.sh |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/mountdevsubfs.sh |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/mountkernfs.sh |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/mountnfs-bootclean.sh |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/mountnfs.sh |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/mtab.sh |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/networking |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/procps |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/rc |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/rc.local |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/rcS |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/reboot |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/rmnologin |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/rsyslog |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/screen-cleanup |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/sendsigs |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/single |
| file_acl | NOT: **2,**3,**6,**7 | 644 | /etc/init.d/skeleton |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/ssh |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/sudo |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/udev |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/udev-mtab |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/umountfs |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/umountnfs.sh |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/umountroot |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/unattended-upgrades |
| file_acl | NOT: **2,**3,**6,**7 | 755 | /etc/init.d/urandom |
| dir_owner_gid | root | root | /etc/init.d |
| file_owner_gid | root | root | /etc/init.d/README |
| file_owner_gid | root | root | /etc/init.d/apache2 |
| file_owner_gid | root | root | /etc/init.d/bootlogs |
| file_owner_gid | root | root | /etc/init.d/bootmisc.sh |
| file_owner_gid | root | root | /etc/init.d/checkfs.sh |
| file_owner_gid | root | root | /etc/init.d/checkroot-bootclean.sh |
| file_owner_gid | root | root | /etc/init.d/checkroot.sh |
| file_owner_gid | root | root | /etc/init.d/cloud-config |
| file_owner_gid | root | root | /etc/init.d/cloud-final |
| file_owner_gid | root | root | /etc/init.d/cloud-init |
| file_owner_gid | root | root | /etc/init.d/cloud-init-local |
| file_owner_gid | root | root | /etc/init.d/cphalod |
| file_owner_gid | root | root | /etc/init.d/cron |
| file_owner_gid | root | root | /etc/init.d/halt |
| file_owner_gid | root | root | /etc/init.d/hostname.sh |
| file_owner_gid | root | root | /etc/init.d/hwclock.sh |
| file_owner_gid | root | root | /etc/init.d/killprocs |
| file_owner_gid | root | root | /etc/init.d/kmod |
| file_owner_gid | root | root | /etc/init.d/motd |
| file_owner_gid | root | root | /etc/init.d/mountall-bootclean.sh |
| file_owner_gid | root | root | /etc/init.d/mountall.sh |
| file_owner_gid | root | root | /etc/init.d/mountdevsubfs.sh |
| file_owner_gid | root | root | /etc/init.d/mountkernfs.sh |
| file_owner_gid | root | root | /etc/init.d/mountnfs-bootclean.sh |
| file_owner_gid | root | root | /etc/init.d/mountnfs.sh |
| file_owner_gid | root | root | /etc/init.d/mtab.sh |
| file_owner_gid | root | root | /etc/init.d/networking |
| file_owner_gid | root | root | /etc/init.d/procps |
| file_owner_gid | root | root | /etc/init.d/rc |
| file_owner_gid | root | root | /etc/init.d/rc.local |
| file_owner_gid | root | root | /etc/init.d/rcS |
| file_owner_gid | root | root | /etc/init.d/reboot |
| file_owner_gid | root | root | /etc/init.d/rmnologin |
| file_owner_gid | root | root | /etc/init.d/rsyslog |
| file_owner_gid | root | root | /etc/init.d/screen-cleanup |
| file_owner_gid | root | root | /etc/init.d/sendsigs |
| file_owner_gid | root | root | /etc/init.d/single |
| file_owner_gid | root | root | /etc/init.d/skeleton |
| file_owner_gid | root | root | /etc/init.d/ssh |
| file_owner_gid | root | root | /etc/init.d/sudo |
| file_owner_gid | root | root | /etc/init.d/udev |
| file_owner_gid | root | root | /etc/init.d/udev-mtab |
| file_owner_gid | root | root | /etc/init.d/umountfs |
| file_owner_gid | root | root | /etc/init.d/umountnfs.sh |
| file_owner_gid | root | root | /etc/init.d/umountroot |
| file_owner_gid | root | root | /etc/init.d/unattended-upgrades |
| file_owner_gid | root | root | /etc/init.d/urandom |

### Critical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| user_has_password | True | True | irc |
| user_has_password | True | True | news |
| user_has_password | True | True | libuuid |
| user_has_password | True | True | lp |
| user_has_password | True | True | list |
| user_has_password | True | True | bin |
| user_has_password | True | True | backup |
| user_has_password | True | True | man |
| user_has_password | True | True | admin |
| user_has_password | True | True | root |
| user_has_password | True | True | uucp |
| user_has_password | True | True | gnats |
| user_has_password | True | True | proxy |
| user_has_password | True | True | games |
| user_has_password | True | True | nobody |
| user_has_password | True | True | sync |
| user_has_password | True | True | sshd |
| user_has_password | True | True | mail |
| user_has_password | True | True | www-data |
| user_has_password | True | True | sys |
| user_has_password | True | True | daemon |

### Critical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| configuration | NOT: yes | no | /etc/ssh/sshd_config |

### Noncritical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| file_regex | False | False | /etc/fstab |

### Noncritical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| password_is_username | False | False | root |
| password_is_username | False | False | daemon |
| password_is_username | False | False | bin |
| password_is_username | False | False | sys |
| password_is_username | False | False | sync |
| password_is_username | False | False | games |
| password_is_username | False | False | man |
| password_is_username | False | False | lp |
| password_is_username | False | False | mail |
| password_is_username | False | False | news |
| password_is_username | False | False | uucp |
| password_is_username | False | False | proxy |
| password_is_username | False | False | www-data |
| password_is_username | False | False | backup |
| password_is_username | False | False | list |
| password_is_username | False | False | irc |
| password_is_username | False | False | gnats |
| password_is_username | False | False | nobody |
| password_is_username | False | False | libuuid |
| password_is_username | False | False | sshd |
| password_is_username | False | False | admin |
| user_has_password | True | True | irc |
| user_has_password | True | True | news |
| user_has_password | True | True | libuuid |
| user_has_password | True | True | lp |
| user_has_password | True | True | list |
| user_has_password | True | True | bin |
| user_has_password | True | True | backup |
| user_has_password | True | True | man |
| user_has_password | True | True | admin |
| user_has_password | True | True | root |
| user_has_password | True | True | uucp |
| user_has_password | True | True | gnats |
| user_has_password | True | True | proxy |
| user_has_password | True | True | games |
| user_has_password | True | True | nobody |
| user_has_password | True | True | sync |
| user_has_password | True | True | sshd |
| user_has_password | True | True | mail |
| user_has_password | True | True | www-data |
| user_has_password | True | True | sys |
| user_has_password | True | True | daemon |
| file_regex | False | False | /etc/passwd |

### Noncritical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| file_presence | True | True | /etc/shells |
| file_regex | True | True | /etc/shells |

### Noncritical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| file_regex | False | False | /etc/passwd |
| file_regex | False | False | /etc/passwd |

### Noncritical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| file_presence | True | True | /etc/login.defs |

### Noncritical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| file_presence | True | True | /var/log/auth.log |

### Noncritical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| file_regex | False | False | /etc/group |
| file_regex | False | False | /etc/group |
| file_regex | False | False | /etc/group |
| file_regex | False | False | /etc/group |

### Noncritical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| password_not_expired | True | True | root |
| password_not_expired | True | True | daemon |
| password_not_expired | True | True | bin |
| password_not_expired | True | True | sys |
| password_not_expired | True | True | sync |
| password_not_expired | True | True | games |
| password_not_expired | True | True | man |
| password_not_expired | True | True | lp |
| password_not_expired | True | True | mail |
| password_not_expired | True | True | news |
| password_not_expired | True | True | uucp |
| password_not_expired | True | True | proxy |
| password_not_expired | True | True | www-data |
| password_not_expired | True | True | backup |
| password_not_expired | True | True | list |
| password_not_expired | True | True | irc |
| password_not_expired | True | True | gnats |
| password_not_expired | True | True | nobody |
| password_not_expired | True | True | libuuid |
| password_not_expired | True | True | sshd |
| password_not_expired | True | True | admin |

### Critical Finding!| Type | Expected | Actual | Target |
|------|----------|--------|--------|
| process_presence | false | false | in.inetd |
| process_presence | false | false | inetd |
| process_presence | false | false | in.xinetd |
| process_presence | false | false | xinetd |

**Comment by doolin** [comment]
sweet

**Comment by ashmastaflash** [comment]
killing
